# Generated by Django 6.0.4 on 2026-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='career_objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
