# Generated by Django 6.0.4 on 2026-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_resume_career_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
